trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals test-deneme

# variables:
#   ANDROID_HOME: 'C:\\Path\\To\\Your\\Android\\Sdk'  # Android SDK yolunu burada belirtin

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: './gradlew assembleDebug'