trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals test-deneme

variables:
  ANDROID_HOME: 'C:\Users\Burhan Ferit\AppData\Local\Android\Sdk'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
- script: |
    echo Starting Gradle Build
    ./gradlew assembleDebug
  displayName: 'Run Gradle Build'
  env:
    ANDROID_HOME: $(ANDROID_HOME)